### PR TITLE
Support Vite 6

### PR DESCRIPTION
**Pull request by jochensengier**
Support Vite 6

### CODE REVIEW

**Review by iBotPeaches — COMMENTED** [review]
Shouldn't the yarn lock change as well?

**Review by iBotPeaches — CHANGES_REQUESTED** [review]
You added a `package-lock.json` file now :/ - this project has a `yarn.lock` file

**Comment by jochensengier** [comment]
> You added a `package-lock.json` file now :/ - this project has a `yarn.lock` file

Whoops 😅

**Review by iBotPeaches — APPROVED** [review]

**Comment by erbelion** [comment]
thanks

**Pull request merged**
